### ISSUE TITLE
New feature: Get data filtered from response

### ISSUE THREAD

**Issue by agraciakuvut** [buuum/RequestCheck#1]
Cambiar la función validate para que filtre y valide y el objecto response tenga una función que devuelve el data filtrado.

Quizás cambiar el nombre de la función validate y que la función filter no sea publica mejoraría la lógica de como funciona el request.

**Comment by buuum** [comment]
Ahora es checkRequest()
devuelve un requestResponse que tiene el metodo getData

Esta todo en el readme.
